Repository qiniu/go-sdk, pull requests merged in 2023-06, with the labels that each got.

#95 add BucketManager.SetRemark / BucketManager.BucketsV2
  storage/bucket.go
  storage/bucket_test.go
  storage/buckets_v4.go
  storage/uc.go
Labels: size/L

#101 uc query api: backup host add api.qiniu.com
  internal/clientv2/interceptor_retry_hosts_test.go
  internal/clientv2/interceptor_retry_simple_test.go
  storage/region.go
  storage/region_uc_v2.go
  storage/region_uc_v4.go
  storage/uc.go
Labels: size/M

#102 version to v1.17.0
  CHANGELOG.md
  README.md
  conf/conf.go
Labels: size/XS
