Repository qiniu/go-sdk, pull requests merged in 2023-09, with the labels that each got.

#106 Add ChangeMimeAndMeta & ChangeMeta
  storage/bucket.go
  storage/bucket_test.go
  storage/form_upload.go
  storage/resume_uploader_apis.go
  storage/upload_manager.go
Labels: size/L

#111 将 staticcheck 作为 ci 检查内容
  .github/workflows/ci-test.yml
  Makefile
  client/client.go
  doc.go
  err.go
  internal/clientv2/interceptor_debug.go
  linking/device.go
  rtc/util.go
  storage/bucket.go
  storage/bucket_test.go
  storage/errs.go
  storage/form_upload.go
  storage/pfop.go
  storage/region.go
  storage/region_uc_v2.go
  storage/region_uc_v4.go
  storage/resume_uploader.go
  storage/resume_uploader_base.go
  storage/uploader_base.go
  storage/util.go
  types.go
Labels: size/L

#110 UC 查询缓存键包含 UC 地址
  storage/region_uc_v2.go
  storage/region_uc_v4.go
Labels: size/M

#112 try to keep code compatibility
  client/client.go
  storage/errs.go
Labels: size/XS
